import 'models.dart';

class MockData {
  static final List<Teacher> teachers = [
    Teacher(
      id: 't1',
      name: '林然',
      title: '财富管理导师',
      avatarUrl: '',
      bio: '10 年投研与实战培训经验，擅长资产配置与风控。',
      tags: ['财富管理', '资产配置', '风控'],
      wins: 28,
      losses: 6,
      rating: 96,
      todayStrategy: '稳健型配置：核心仓位控制 60%，分散至低波动资产。',
      strategyHistory: [
        StrategyItem(
          id: 'st1',
          title: '防御型组合调整',
          summary: '适度降低权益仓位，提升流动性。',
          date: '2026-02-07',
        ),
        StrategyItem(
          id: 'st2',
          title: '均衡型配置思路',
          summary: '保持中性仓位，关注估值修复机会。',
          date: '2026-02-05',
        ),
      ],
      trades: [
        TradeRecord(
          id: 'tr1',
          asset: '中证红利ETF',
          buyTime: '2026-02-05',
          buyShares: '2,000',
          buyPrice: '98.50',
          sellTime: '2026-02-07',
          sellShares: '2,000',
          sellPrice: '103.20',
          pnlRatio: 4.8,
          pnlAmount: 9600,
        ),
        TradeRecord(
          id: 'tr2',
          asset: '国债ETF',
          buyTime: '2026-02-01',
          buyShares: '1,500',
          buyPrice: '102.10',
          sellTime: '2026-02-04',
          sellShares: '1,500',
          sellPrice: '100.90',
          pnlRatio: -1.2,
          pnlAmount: -1800,
        ),
      ],
      positions: [
        PositionRecord(
          id: 'p1',
          asset: '稳健债券',
          buyTime: '2026-01-20',
          buyShares: '2,000',
          buyPrice: '98.50',
          costPrice: '98.10',
          currentPrice: '101.20',
          floatingPnl: 3400,
          pnlRatio: 3.2,
          pnlAmount: 3200,
        ),
        PositionRecord(
          id: 'p2',
          asset: '红利指数',
          buyTime: '2026-01-12',
          buyShares: '1,500',
          buyPrice: '102.30',
          costPrice: '101.80',
          currentPrice: '106.90',
          floatingPnl: 6900,
          pnlRatio: 4.5,
          pnlAmount: 6800,
        ),
        PositionRecord(
          id: 'p3',
          asset: '工商银行',
          buyTime: '2026-01-05',
          buyShares: '4,000',
          buyPrice: '1.00',
          costPrice: '1.00',
          currentPrice: '1.01',
          floatingPnl: 1600,
          pnlRatio: 0.4,
          pnlAmount: 1600,
        ),
      ],
      historyPositions: [
        PositionRecord(
          id: 'hp1',
          asset: '国债ETF',
          buyTime: '2025-12-10',
          buyShares: '1,200',
          buyPrice: '101.40',
          costPrice: '101.10',
          currentPrice: '100.20',
          floatingPnl: -1100,
          pnlRatio: -0.9,
          pnlAmount: -1100,
        ),
        PositionRecord(
          id: 'hp2',
          asset: '中证红利ETF',
          buyTime: '2025-11-18',
          buyShares: '1,800',
          buyPrice: '96.20',
          costPrice: '96.00',
          currentPrice: '99.80',
          floatingPnl: 6400,
          pnlRatio: 3.7,
          pnlAmount: 6400,
        ),
      ],
      pnlCurrent: 18600,
      pnlMonth: 35600,
      pnlYear: 128400,
      pnlTotal: 356900,
      comments: [
        Comment(
          id: 'c1',
          userName: '学员-阿星',
          content: '策略思路很清晰，节奏把握到位。',
          date: '2026-02-08',
        ),
        Comment(
          id: 'c2',
          userName: '学员-乐乐',
          content: '希望能多分享一些风控细节。',
          date: '2026-02-07',
        ),
      ],
      articles: [
        Article(
          id: 'a1',
          title: '资金管理的三条底线',
          summary: '建立纪律框架，先活下来再成长。',
          date: '2026-02-01',
        ),
      ],
      schedules: [
        ScheduleItem(
          id: 's1',
          title: '公开课：稳健型资产配置',
          date: '2026-02-10 19:30',
          location: '线上直播',
        ),
      ],
    ),
    Teacher(
      id: 't2',
      name: '周远',
      title: '量化交易导师',
      avatarUrl: '',
      bio: '量化策略研发与回测专家，专注策略构建与执行。',
      tags: ['量化', '策略', '回测'],
      wins: 34,
      losses: 4,
      rating: 99,
      todayStrategy: '趋势跟随：控制单策略回撤，核心仓位不追高。',
      strategyHistory: [
        StrategyItem(
          id: 'st3',
          title: '因子轮动跟踪',
          summary: '跟随高动量板块，减少拥挤度。',
          date: '2026-02-06',
        ),
      ],
      trades: [
        TradeRecord(
          id: 'tr3',
          asset: '量化多因子',
          buyTime: '2026-02-03',
          buyShares: '3,000',
          buyPrice: '112.40',
          sellTime: '2026-02-06',
          sellShares: '3,000',
          sellPrice: '119.50',
          pnlRatio: 6.3,
          pnlAmount: 18900,
        ),
      ],
      positions: [
        PositionRecord(
          id: 'p4',
          asset: '中性策略',
          buyTime: '2026-01-18',
          buyShares: '3,000',
          buyPrice: '112.40',
          costPrice: '111.90',
          currentPrice: '118.70',
          floatingPnl: 12600,
          pnlRatio: 5.6,
          pnlAmount: 12400,
        ),
        PositionRecord(
          id: 'p5',
          asset: '趋势策略',
          buyTime: '2026-01-15',
          buyShares: '2,500',
          buyPrice: '108.80',
          costPrice: '108.20',
          currentPrice: '112.70',
          floatingPnl: 10000,
          pnlRatio: 4.1,
          pnlAmount: 9800,
        ),
      ],
      historyPositions: [
        PositionRecord(
          id: 'hp3',
          asset: '量化多因子',
          buyTime: '2025-10-12',
          buyShares: '2,400',
          buyPrice: '108.30',
          costPrice: '108.00',
          currentPrice: '104.10',
          floatingPnl: -9900,
          pnlRatio: -3.6,
          pnlAmount: -9900,
        ),
      ],
      pnlCurrent: 22400,
      pnlMonth: 61200,
      pnlYear: 198900,
      pnlTotal: 522300,
      comments: [
        Comment(
          id: 'c3',
          userName: '学员-鹏鹏',
          content: '实操性很强，期待下次直播。',
          date: '2026-02-06',
        ),
      ],
      articles: [
        Article(
          id: 'a2',
          title: '如何搭建可落地的量化策略',
          summary: '从数据、逻辑到执行的完整路径。',
          date: '2026-02-03',
        ),
      ],
      schedules: [
        ScheduleItem(
          id: 's2',
          title: '量化训练营',
          date: '2026-02-12 09:00',
          location: '线下·A 教室',
        ),
      ],
    ),
    Teacher(
      id: 't3',
      name: '何晴',
      title: '基金研究导师',
      avatarUrl: '',
      bio: '长期跟踪公募与行业研究，擅长组合优化。',
      tags: ['基金', '研究', '组合'],
      wins: 21,
      losses: 9,
      rating: 91,
      todayStrategy: '低波动配置：优先高分红与固收增强。',
      strategyHistory: [
        StrategyItem(
          id: 'st4',
          title: '基金久期调整',
          summary: '适度拉长久期，兼顾收益与稳健。',
          date: '2026-02-06',
        ),
      ],
      trades: [
        TradeRecord(
          id: 'tr4',
          asset: '固收增强',
          buyTime: '2026-02-02',
          buyShares: '1,800',
          buyPrice: '99.20',
          sellTime: '2026-02-05',
          sellShares: '1,800',
          sellPrice: '98.60',
          pnlRatio: -0.6,
          pnlAmount: -720,
        ),
      ],
      positions: [
        PositionRecord(
          id: 'p6',
          asset: '固收增强',
          buyTime: '2026-01-10',
          buyShares: '1,800',
          buyPrice: '99.20',
          costPrice: '99.10',
          currentPrice: '98.40',
          floatingPnl: -1300,
          pnlRatio: -0.7,
          pnlAmount: -1200,
        ),
        PositionRecord(
          id: 'p7',
          asset: '高股息',
          buyTime: '2026-01-08',
          buyShares: '1,200',
          buyPrice: '86.40',
          costPrice: '86.10',
          currentPrice: '88.10',
          floatingPnl: 2500,
          pnlRatio: 2.0,
          pnlAmount: 2400,
        ),
        PositionRecord(
          id: 'p8',
          asset: '现金',
          buyTime: '2026-01-02',
          buyShares: '10,000',
          buyPrice: '1.00',
          costPrice: '1.00',
          currentPrice: '1.00',
          floatingPnl: 0,
          pnlRatio: 0.0,
          pnlAmount: 0,
        ),
      ],
      historyPositions: [
        PositionRecord(
          id: 'hp4',
          asset: '高股息',
          buyTime: '2025-09-02',
          buyShares: '900',
          buyPrice: '80.20',
          costPrice: '80.10',
          currentPrice: '82.30',
          floatingPnl: 1900,
          pnlRatio: 2.6,
          pnlAmount: 1900,
        ),
      ],
      pnlCurrent: -3600,
      pnlMonth: 12800,
      pnlYear: 68400,
      pnlTotal: 210500,
      comments: [
        Comment(
          id: 'c4',
          userName: '学员-小雨',
          content: '内容实用，建议加一个复盘模块。',
          date: '2026-02-05',
        ),
      ],
      articles: [
        Article(
          id: 'a3',
          title: '如何读懂基金季报',
          summary: '从持仓结构看风险与机会。',
          date: '2026-02-05',
        ),
      ],
      schedules: [
        ScheduleItem(
          id: 's3',
          title: '基金研究公开课',
          date: '2026-02-14 15:00',
          location: '线上直播',
        ),
      ],
    ),
  ];

  static final List<RankingEntry> ranking = [
    RankingEntry(teacherId: 't2', score: 98),
    RankingEntry(teacherId: 't1', score: 92),
    RankingEntry(teacherId: 't3', score: 88),
  ];
}
